### ISSUE TITLE
Envs in arguments

### ISSUE THREAD

**Issue by thallesdaniell** [SonarSource/sonarqube-scan-action#11]
In the arguments it is possible to pass as git environment variables ?
test: `${{ PROJECT_NAME }} , $PROJECT_NAME`
```
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
        with:
          args: >
            -Dsonar.projectKey=${{ PROJECT_NAME }}
            -Dsonar.organization=default-organization
```
