### ISSUE TITLE
How to annotate the PR with results? 

### ISSUE THREAD

**Issue by davidhu2000** [SonarSource/sonarqube-scan-action#18]
```yaml
      - name: SonarQube scan for pull request
        if: ${{ github.ref != format('refs/heads/{0}', env.BASE_BRANCH) }}
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
        with:
          args: >
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.key=${{ github.event.number }}
            -Dsonar.pullrequest.base=${{ env.BASE_BRANCH }}

      - name: SonarQube Quality Gate check
        if: ${{ github.ref != format('refs/heads/{0}', env.BASE_BRANCH) }}
        uses: sonarsource/sonarqube-quality-gate-action@master
        # force to fail step after specific time
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
```

we are currently using the scan action + quality gate check action to do sonarqube scans. Is there way to have the action auto annotate the pull request with results? 

currently we need to manually to go into sonarqube to see
