### ISSUE TITLE
Support for 'pull_request_target'

### ISSUE THREAD

**Issue by ad-m-ss** [SonarSource/sonarqube-scan-action#43]
Hi,

We want to activate the correct operation of dependabot with `sonarsource / sonarqube-scan-action`. Due to the required token, the external PR has no access to the secrets. For this reason, we decided to use the action at the "pull_reqest_target" event.

Our workflow for looks:

```yaml
name: SonarQube Analysis

on:
  workflow_run:
    workflows: [Test & Build & Push of Frontend] # keep in sync with build.yml
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Download artifact'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: "code_and_coverage" # keep in sync with build.yml
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
```

We observe strange behavior where SonarQube for pull_requests does not create comments, and is not a quality gate (not even a PR check). I wonder if anyone has experience with this configuration and suggestions.

Kind regards

**Comment by cartucciam** [comment]
We found documentation is lacking on this regards too.

The client only seem to detect a PR when the event triggering it is a PR:
```
on
  pull_request:
     types: [ opened, synchronize, reopened ]
```
and can be checked in the logs
```
INFO: Auto-configuring pull request '123'
```

For anything else you would see
```
INFO: Auto-configuring branch 'testing'
```

---

It would be really nice if the scan could be smarter and detect if there is a PR on its own instead of relying entirely on the client submitting the request

**Comment by kherock** [comment]
Hi I just ran into this today and was disappointed to see that this hasn't been noticed yet -  This has a workaround by setting the properties manually as CLI args:

```yaml
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          args: >
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
```

This issue was raised in a community discussion, but apparently this approach is deprecated:
https://community.sonarsource.com/t/github-pull-request-decoration-and-sonarcloud-code-analysis-check-stopped-working-after-switch-to-pull-request-target/52192
