### ISSUE TITLE
Argument values with spaces don't seem to work

### ISSUE THREAD

**Issue by robtimus** [SonarSource/sonarqube-scan-action#50]
I want to provide the `-Dsonar.projectDescription` as argument. The value contains spaces, which is totally normal for descriptions. I've tried several options with quotes, but all seem to fail.

The argument I want to provide: `-Dsonar.projectDescription=Provides functionality for obfuscating text`

Without any quotes I get this error, which is completely understandable: `ERROR: Unrecognized option: functionality`

With single quotes around the entire thing (`'-Dsonar.projectDescription=Provides functionality for obfuscating text'`) I get this error: `ERROR: Unrecognized option: '-Dsonar.projectDescription=Provides`. In other words, it seems that the split is still on the first space.
With double quotes (`"-Dsonar.projectDescription=Provides functionality for obfuscating text"`) I get the same error but with a `"` instead of a `'`.

With single quotes only around the value (`-Dsonar.projectDescription='Provides functionality for obfuscating text'`) I get the first error: `ERROR: Unrecognized option: functionality`. In other words, it seems that the split is still on the first space.
With double quotes (`-Dsonar.projectDescription="Provides functionality for obfuscating text"`) I get the same error.

Is it possible to provide values that contain multiple words? If so, can you share how? If not, is this something that can be added?

**Comment by marcus-vw** [comment]
Facing the same issue. It doesn't matter how I quote the `-Dsonar.projectDescription` which contains a space, I am always running into `ERROR: Unrecognized option: ...`

**Comment by gouldre** [comment]
I'm getting the same issue with `-Dsonar.projectName`

**Comment by zymotik** [comment]
I also get the same problem with the argument `-Dsonar.projectName`

Example:

```yml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.projectKey=my_app
            -Dsonar.projectName=My Application
            -Dsonar.organization=org
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

I have tried:

```yml
          args: >
            -Dsonar.projectKey=my_app
            -Dsonar.projectName=\"My Application\"
```

```yml
          args: >
            -Dsonar.projectKey=my_app
            -Dsonar.projectName='My Application'
```

As you cannot change the project name in the Sonar Cloud console (which seems like an oddly missing feature), this is causing frustration.

### It's been a year with this *simple* bug! Any idea on a fix timeline please?

I understand this is an open source project and the community could fix it, but we are paying for this product. Your help would be appreciated.
