### ISSUE TITLE
SonarScan - Failed on Self-hosted runner on top of  a docker container

### ISSUE THREAD

**Issue by shivajipotnuru** [SonarSource/sonarqube-scan-action#58]
Hi, 

I'm running my self-hosted runner on a docker container which uses Ubuntu. I have connected the runner with GHE.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/33416266/224038918-93185b68-fef9-44b0-89c0-ba672f95c59d.png">

This action will not work ? if the runner hosted in a docker that's hosted in Azure Container instance (ACI)

My workflow file.
```
name: Code Quality 
on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches:
      - main
      - develop
     
  pull_request:
      types: [opened, synchronize, reopened]
  workflow_dispatch:


jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
```
