### ISSUE TITLE
Code coverage not working when moving the coverage.out across jobs

### ISSUE THREAD

**Issue by cartucciam** [SonarSource/sonarqube-scan-action#61]
EDIT: fixed the example with the working solution

Hi there, I've been trying to use the action on its own job with no success with

_job-a_
```yaml
      - name: Run tests with Coverage
        run: go test -coverprofile coverage.out -tags=integration ./...

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.run_id }}-coverage.out
          path: coverage.out
          retention-days: 5
```

_job-b_
```yaml
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: ${{ github.run_id }}-coverage.out
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ steps.secret_retrieval.outputs.api_token }}
          SONAR_HOST_URL: ${{ env.sonar_host_url }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*_test.go
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.go.coverage.reportPaths=./coverage.out
```

but in the logs I get:
```
Artifact 2471777799-coverage.out was downloaded to /runner/_work/example/example/
```
```
ERROR: Coverage report can't be loaded, report file not found, ignoring this file /runner/_work/example/example/2471777799-coverage.out.
```

I tried different combinations of `name` and `path`, with and without prefixing the `download-path` with no luck. I can see only two instances of this type of solution for a go coverage on search.github.com https://github.com/search?q=%22download-artifact%22+%22sonarqube-scan-action%22+path%3A%22.github%22+%22coverage.out%22&type=code and I don't know what I am doing differently
