### ISSUE TITLE
Unable to post using custom headers passed to GH action

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [SonarSource/sonarqube-scan-action#66]
I am using the action as follows to post to a cloudflare protected SQ instance

```
      - name: post results to SQ
        uses: sonarsource/sonarqube-scan-action@v1.2.0
        with:
          args: >
            -Dsonar.ws.headers="CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}, CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_API_TOKEN }}
          SONAR_HOST_URL: https://my-sonarqube.instance.com
```

Ηere are the execution logs:

```
Run sonarsource/sonarqube-scan-action@v1.2.0
  with:
    args: -Dsonar.ws.headers="CF-Access-Client-Id: ***, CF-Access-Client-Secret: ***"
  
    projectBaseDir: .
  env:
    SONAR_TOKEN: 
    SONAR_HOST_URL: https://my-sonarqube.instance.com
```

```
ERROR: Unrecognized option: ***,
INFO: 
INFO: usage: sonar-scanner [options]
INFO: 
INFO: Options:
INFO:  -D,--define <arg>     Define property
INFO:  -h,--help             Display help information
INFO:  -v,--version          Display version information
INFO:  -X,--debug            Produce execution debug output
```

Why is the command failing it is entirety and interpreting the scrambled sensitive values as options?
