### ISSUE TITLE
Cache: A way to save the cache using GitHub Actions

### ISSUE THREAD

**Issue by dardaiin** [SonarSource/sonarqube-scan-action#72]
I'm trying to cache the SonarQube run in GitHub actions using this: [actions/cache@v3](https://github.com/actions/cache/tree/v3/). 

I have tried using `~/.sonar/cache` and also `/opt/sonar-scanner/.sonar/cache`

Any ideas on what am missing, thank you! 

My action: 

```
      - name: actions/cache - sonar/cache
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: sonarqube-${{ runner.os }}-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: |
            sonarqube-${{ runner.os }}-
```
