### ISSUE TITLE
Scan not pushing correct branch names and PR details

### ISSUE THREAD

**Issue by ealves-pt** [SonarSource/sonarqube-scan-action#8]
My workflow looks like the following:

```yaml
name: Lint, Test, & Scan

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    tags:
      - v*
    branches:
      - main

  lint:
    # Details not relevant...
  test:
    # Details not relevant...

  scan:
    name: scan
    needs: [ lint, test ]
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Download test report
      - name: Download test report
        uses: actions/download-artifact@v2
        with:
          name: test-report
          path: ./reports/
      # Download lint report
      - name: Download lint report
        uses: actions/download-artifact@v2
        with:
          name: lint-report
          path: ./reports/
      # Scan with SonarQube
      - name: Run SonarQube scanner
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
```

All the steps run successfully but the scan results are always pushed to the **master** branch in SonarQube, ignoring completely the actual details from GitHub.

Shouldn't this action be able to detect the branch name, the PR details and process that info accordingly? If not, how do you suggest that I fix this?

I'm using SonarQube Developer Edition.
