### ISSUE TITLE
Sonar scan not work anymore after release v2.0.0 last night

### ISSUE THREAD

**Issue by longdl97** [SonarSource/sonarqube-scan-action#80]
At this morning, my project CI throwing java exception after one run:
<img width="1104" alt="image" src="https://github.com/SonarSource/sonarqube-scan-action/assets/68152546/dc714c5d-c6e0-4fb6-8f90-38ad54b51ead">
<img width="1103" alt="image" src="https://github.com/SonarSource/sonarqube-scan-action/assets/68152546/372adcb7-9709-4cac-9a31-36f9064cd7d4">
It works very well yesterday.
My github flow config:
```
sonar-scan:
    name: Sonar scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
sonar-project.properties:
```
sonar.host.url=https://sonar.dgg.network
sonar.projectKey=gameguild-backend
sonar.projectName=gameguild-backend
sonar.projectVersion=1.0

sonar.sources=controllers,helpers,migrations,models,resources,routes,views
sonar.language=js

sonar.sourceEncoding=UTF-8
```
It still work if i use token to run sonar-scan cli from local
<img width="929" alt="image" src="https://github.com/SonarSource/sonarqube-scan-action/assets/68152546/000182a1-9df7-42de-b743-30a79678a027">
So I think something wrong with my ci/cd.
What do i have change in version v2.0.0 or how to treat with this?
