### ISSUE TITLE
MacOS - Container action is only supported on Linux

### ISSUE THREAD

**Issue by salvatoreboemia** [SonarSource/sonarqube-scan-action#90]
Hi

I want to integrate Sonarqube scan (I already have a dashboard), I have migrated the Swift/Objc-C) repo from Azure to GitHub

I started from here

<img width="692" alt="image" src="https://github.com/SonarSource/sonarqube-scan-action/assets/20614870/f12dea2c-d400-4bc3-90c8-fa4d7809f987">

After that, I changed something and translate other things from Azure Pipeline to GitHub Action

This is some few row

```
on:
  #schedule:
   # - cron: '0 22 * * *'
  workflow_dispatch:
jobs:
  Analysis:
  # use mac-os machine
    runs-on: ${{ vars.MY_MAC}}

  # create a checkout fetch 1 to develoment branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: development
```

But I got this error

`Container action is only supported on Linux` on Analysis 

How can solve this step in order to publish my code to my sonarqube dashboard? (I also link DevOps on SonarQube Dashboard)

Thanks

EDIT

could I add this step?

```
- name: Install SonarScanner
        run: |
          brew install sonar-scanner
        shell: bash
```
